name: ci

on:
  push:
    branches:
      - main

jobs:
  test-build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.6'
        bundler-cache: true
    - name: Cache gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-ci-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-ci-
    - name: Install Dependencies
      run: |
        gem install bundler -v 1.17.3
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Pre-compile assets
      run: bundle exec rake assets:precompile
    #- name: Run RuboCop
      #run: bundle exec rubocop --parallel
    - uses: nanasess/setup-chromedriver@master
    - name: Setup Datatbase
      run: |
            bundle exec rake db:migrate
    - name: Run tests
      env:
        APP_URL: http://127.0.0.1:3333
        DATABASE_URL: sqlite3:///db/test.sqlite3
      run: |
        bundle exec rake db:migrate RAILS_ENV=test
        bundle exec rake parallel:spec
    - name: Upload rspec screenshots
      if: ${{ job.status != 'success' }}
      uses: actions/upload-artifact@master
      with:
        name: rspec-screenshots
        path: tmp/screenshots
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PWD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: jesser01/blog:latest